# Generated by Django 4.1.12 on 2024-01-06 13:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('buy_price', models.FloatField()),
                ('buy_amount', models.FloatField()),
                ('buy_total', models.FloatField()),
                ('indicators', models.CharField(blank=True, max_length=255, null=True)),
                ('buy_created_at', models.DateTimeField(default=datetime.datetime(2024, 1, 6, 16, 37, 55, 646356))),
                ('buy_updated_at', models.DateTimeField(default=datetime.datetime(2024, 1, 6, 16, 37, 55, 646356))),
            ],
            options={
                'db_table': 'buy_orders',
            },
        ),
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=30)),
                ('price', models.FloatField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('available', models.FloatField(blank=True, null=True)),
                ('periority', models.BooleanField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 1, 6, 16, 37, 55, 644303))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 1, 6, 16, 37, 55, 644303))),
            ],
            options={
                'db_table': 'Coin',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('info', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('function_name', models.CharField(max_length=255)),
                ('balance', models.FloatField(blank=True, null=True)),
                ('periority', models.BooleanField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 1, 6, 16, 37, 55, 645349))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 1, 6, 16, 37, 55, 645349))),
            ],
            options={
                'db_table': 'strategy',
                'unique_together': {('name', 'function_name')},
            },
        ),
        migrations.CreateModel(
            name='StrategyTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_frame', models.CharField(max_length=10)),
                ('periority', models.BooleanField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 1, 6, 16, 37, 55, 645349))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 1, 6, 16, 37, 55, 645349))),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.strategy')),
            ],
            options={
                'db_table': 'strategy_times',
                'unique_together': {('time_frame', 'strategy')},
            },
        ),
        migrations.CreateModel(
            name='SellOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sell_price', models.FloatField()),
                ('sell_amount', models.FloatField()),
                ('sell_total', models.FloatField()),
                ('profit', models.FloatField()),
                ('indicators', models.CharField(blank=True, max_length=255, null=True)),
                ('sell_created_at', models.DateTimeField(default=datetime.datetime(2024, 1, 6, 16, 37, 55, 646356))),
                ('sell_updated_at', models.DateTimeField(default=datetime.datetime(2024, 1, 6, 16, 37, 55, 646356))),
                ('buy_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.buyorder')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.coin')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.strategy')),
                ('time_frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.strategytime')),
            ],
            options={
                'db_table': 'sell_orders',
            },
        ),
        migrations.AddField(
            model_name='buyorder',
            name='coin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.coin'),
        ),
        migrations.AddField(
            model_name='buyorder',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.strategy'),
        ),
        migrations.AddField(
            model_name='buyorder',
            name='time_frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.strategytime'),
        ),
    ]
