# Generated by Django 4.1.12 on 2024-01-03 18:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('buy_price', models.FloatField()),
                ('buy_amount', models.FloatField()),
                ('buy_total', models.FloatField()),
                ('buy_created_at', models.DateTimeField(default=datetime.datetime(2024, 1, 3, 21, 22, 7, 295456))),
                ('buy_updated_at', models.DateTimeField(default=datetime.datetime(2024, 1, 3, 21, 22, 7, 295456))),
            ],
            options={
                'db_table': 'buy_orders',
            },
        ),
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=30)),
                ('price', models.FloatField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('available', models.FloatField(blank=True, null=True)),
                ('periority', models.BooleanField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 1, 3, 21, 22, 7, 295456))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 1, 3, 21, 22, 7, 295456))),
            ],
            options={
                'db_table': 'Coin',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('info', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SellOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sell_price', models.FloatField()),
                ('sell_amount', models.FloatField()),
                ('sell_total', models.FloatField()),
                ('profit', models.FloatField()),
                ('sell_created_at', models.DateTimeField(default=datetime.datetime(2024, 1, 3, 21, 22, 7, 296491))),
                ('sell_updated_at', models.DateTimeField(default=datetime.datetime(2024, 1, 3, 21, 22, 7, 296491))),
                ('buy_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sell_order', to='home.buyorder')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_orders', to='home.coin')),
            ],
            options={
                'db_table': 'sell_orders',
            },
        ),
        migrations.AddField(
            model_name='buyorder',
            name='coin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_orders', to='home.coin'),
        ),
    ]
