# Generated by Django 4.1.12 on 2024-01-07 22:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_strategytime_balance_alter_buyorder_buy_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('log', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 1, 7, 22, 23, 35, 62862))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 1, 7, 22, 23, 35, 62862))),
            ],
        ),
        migrations.AddField(
            model_name='strategy',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strategytime',
            name='amount_per_order',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strategytime',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buyorder',
            name='buy_created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 22, 23, 35, 61867)),
        ),
        migrations.AlterField(
            model_name='buyorder',
            name='buy_updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 22, 23, 35, 61867)),
        ),
        migrations.AlterField(
            model_name='coin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 22, 23, 35, 59861)),
        ),
        migrations.AlterField(
            model_name='coin',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 22, 23, 35, 59861)),
        ),
        migrations.AlterField(
            model_name='sellorder',
            name='sell_created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 22, 23, 35, 61867)),
        ),
        migrations.AlterField(
            model_name='sellorder',
            name='sell_updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 22, 23, 35, 61867)),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 22, 23, 35, 60861)),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 22, 23, 35, 60861)),
        ),
        migrations.AlterField(
            model_name='strategytime',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 22, 23, 35, 60861)),
        ),
        migrations.AlterField(
            model_name='strategytime',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_times', to='home.strategy'),
        ),
        migrations.AlterField(
            model_name='strategytime',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 22, 23, 35, 60861)),
        ),
    ]
