# Generated by Django 4.1.12 on 2024-01-09 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_log_strategy_notes_strategytime_amount_per_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategytime',
            name='stop_loss_percent',
            field=models.FloatField(blank=True, null=True),
        ),

    ]
