# Generated by Django 5.0.1 on 2024-01-13 23:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_strategytime_stop_loss_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyorder',
            name='buy_created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 13, 23, 46, 6, 436125)),
        ),
        migrations.AlterField(
            model_name='buyorder',
            name='buy_updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 13, 23, 46, 6, 436125)),
        ),
        migrations.AlterField(
            model_name='coin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 13, 23, 46, 6, 434125)),
        ),
        migrations.AlterField(
            model_name='coin',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 13, 23, 46, 6, 434125)),
        ),
        migrations.AlterField(
            model_name='log',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 13, 23, 46, 6, 437085)),
        ),
        migrations.AlterField(
            model_name='log',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 13, 23, 46, 6, 437085)),
        ),
        migrations.AlterField(
            model_name='sellorder',
            name='sell_created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 13, 23, 46, 6, 437085)),
        ),
        migrations.AlterField(
            model_name='sellorder',
            name='sell_updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 13, 23, 46, 6, 437085)),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 13, 23, 46, 6, 434125)),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 13, 23, 46, 6, 434125)),
        ),
        migrations.AlterField(
            model_name='strategytime',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 13, 23, 46, 6, 435125)),
        ),
        migrations.AlterField(
            model_name='strategytime',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 13, 23, 46, 6, 435125)),
        ),
    ]
