# Generated by Django 5.0.1 on 2024-02-15 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_strategy_strategy_profit_coin_strategy_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='market_cap',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buyorder',
            name='buy_created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 15, 22, 6, 9, 585785, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='buyorder',
            name='buy_updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 15, 22, 6, 9, 585785, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='coin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 15, 22, 6, 9, 583784, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='coin',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 15, 22, 6, 9, 583784, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='log',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 15, 22, 6, 9, 586785, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='log',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 15, 22, 6, 9, 586785, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sellorder',
            name='sell_created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 15, 22, 6, 9, 585785, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sellorder',
            name='sell_updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 15, 22, 6, 9, 585785, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 15, 22, 6, 9, 583784, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 15, 22, 6, 9, 583784, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='strategytime',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 15, 22, 6, 9, 584785, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='strategytime',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 15, 22, 6, 9, 584785, tzinfo=datetime.timezone.utc)),
        ),
    ]
