# Generated by Django 5.0.1 on 2024-02-23 22:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_coin_market_cap_alter_buyorder_buy_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyorder',
            name='buy_created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 23, 22, 59, 3, 346969, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='buyorder',
            name='buy_updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 23, 22, 59, 3, 347972, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='buyorder',
            name='indicators',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 23, 22, 59, 3, 345970, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='coin',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 23, 22, 59, 3, 345970, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='log',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 23, 22, 59, 3, 348971, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='log',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 23, 22, 59, 3, 348971, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sellorder',
            name='indicators',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='sellorder',
            name='sell_created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 23, 22, 59, 3, 347972, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sellorder',
            name='sell_updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 23, 22, 59, 3, 347972, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 23, 22, 59, 3, 345970, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 23, 22, 59, 3, 345970, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='strategytime',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 23, 22, 59, 3, 346969, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='strategytime',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 23, 22, 59, 3, 346969, tzinfo=datetime.timezone.utc)),
        ),
    ]
